config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users, only: %i[new create edit update]
  resources :opinions, only: %i[new create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'follow', to: 'followings#create'
  
  get 'users/:username', to: 'users#show', as: 'profile'


  post 'likes/:opinion_id', to: 'likes#create', as: 'likes'
  delete 'like', to: 'likes#destroy'
end

app/views/layouts/_aside_index.html.erb
<aside class="rigth-navbar  border border-top-0">
  <div>
    <h6 class="border-bottom p-3 text-muted">
        WHO TO FOLLOW
    </h6>
  </div>
  <% @not_following.each do |not_following| %>
  <div class="d-flex flex-row align-items-center m-auto p-3 shadow rounded">
    <div>
      <%= display_follow_btn(not_following, 'layouts/follow_icon') %>
    </div>
    <div >
      <%= display_photo_profile(not_following, :medium)  %>
    </div>
    <div>
      <h6>
        <strong>
          <%= link_to not_following.fullname, profile_path(not_following.username), class: "text-dark" %>
        </strong>
      </h6>
      <small class="text-muted">
        <%= display_follower_count(not_following) %>
      </small>
    </div>
  </div>
  <% end %>
  <div class="container p-3">
    <small class="text-muted">
        <a href="#">Popular accounts</a> |
        <a href="#">Find friends</a>
    </small>
  </div>
  <div class="d-flex flex-row align-items-center justify-content-between border-top border-bottom px-4 pt-1">
    <h6 class="text-muted  p-3 ">TRENDING</h6><ion-icon name="settings" class="text-muted p-3"></ion-icon>
  </div>
  <div class="p-3 px-5">
  
    <p><a href="#" class="text-muted"> #Football </a></p>
    <p><a href="#" class="text-muted"> #Sport </a></p>
    <p><a href="#" class="text-muted"> #ReggaetonPerreo </a></p>
    <p><a href="#" class="text-muted"> #Games </a></p>
    <p><a href="#" class="text-muted"> #100DaysOfCode </a></p>
  </div>
  </aside>

app/views/layouts/_follow_icon.html.erb
<%= link_to follow_path(user_id: obj.id), method: :post do %>
  <%= follow_icon %>
<% end %>

app/views/layouts/_form_sessions.html.erb
<%= yield %>

app/views/layouts/_main_app.html.erb
<%= render 'layouts/navbar' %>  
<div class="middle-content mx-4 pt-3">
  <%= yield %>
</div>
<%= render 'layouts/sidebar_left' %>
<%= render 'layouts/sidebar_rigth' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light my-bg-primary border-bottom top-navbar">
  <%= link_to root_path, class: "navbar-brand img-fluid " do %>
    <%= image_tag('logo.svg', alt: 'Description', style: 'width:50px; height:50px')%>
  <% end %>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item mx-3">
      <%= link_to root_path, class: 'navbar-item h3 tex-darker' do%>
        <ion-icon name="pencil-outline"></ion-icon>
      <% end %>
    </li>
    <li class="nav-item mx-3">
      <%= link_to root_path, class: 'navbar-item h3 tex-darker' do%>
        <ion-icon name="mail"></ion-icon>
      <% end %>
    </li>
    <li class="nav-item mx-3">
      <%= link_to root_path, class: 'navbar-item h3 tex-darker' do%>
        <ion-icon name="search-outline"></ion-icon>
      <% end %>
    </li>
    <li class="nav-item mx-3">
      <%= link_to edit_user_path(current_user), class: 'navbar-item h3 tex-darker' do%>
        <ion-icon name="settings"></ion-icon>
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/_sidebar_left.html.erb
<aside class="left-navbar my-bg-darker container px-0" >
  <div class="d-flex flex-row align-items-center m-auto p-3">
    <%= display_photo_profile(current_user, :thumb) %>
    <%= link_to current_user.fullname, profile_path(current_user.username), 
    class: "col-6 text-secondary text-uppercase | mx-auto   my-auto |  p-2 | font-weight-bold ", 
    style: "min-width: 200px;" %>
  </div>
  <div class="follow-count-container row mx-4 ">
    <div class="col-6 text-center p-3 list-group-item">
      <h5 class="text-light"><%= current_user.followings.length %></h5>
      <p class="text-light">Following</p>
    </div>
    <div class="col-6 text-center list-group-item p-3">
      <h5 class="text-light"><%= current_user.followers.length %></h5>
      <p class="text-light">Followers</p>
    </div>
  </div>
  <div class="list-group rounded-0">
    <%= link_to root_path, class: "text-light list-group-item list-group-item-action pl-5" do %>
      <ion-icon name="home" class="mr-2"></ion-icon> Home
    <% end %>
    <%= link_to "#", class: "text-light list-group-item list-group-item-action pl-5" do %>
      <ion-icon name="at-outline"class="mr-2"></ion-icon>  Connect
    <% end %>
    <%= link_to  root_path, class: "text-light list-group-item list-group-item-action pl-5" do%>
      <ion-icon name="chatbox"class="mr-2"></ion-icon>  Discover
    <% end %>

    <%= link_to  profile_path(current_user.username), class: "text-light list-group-item list-group-item-action pl-5" do %>
      <ion-icon name="person"class="mr-2"></ion-icon> Profile
    <% end %>
    <%= link_to logout_path, method: :delete, class: "text-light list-group-item list-group-item-action pl-5" do%>
      <ion-icon name="log-out-outline"class="mr-2"></ion-icon> Log out
    <% end %>
  </div>
</aside>

app/views/layouts/_sidebar_rigth.html.erb
<%= show_sidebar %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MCASocial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
  </head>

  <body >
    <div class="alert-container">
      <% flash.each do |key, value|%>
        <div class="alert alert-info" role="alert">
          <button type="button" class="close ml-2" data-dismiss="alert">&times;</button>
          <%=value%>
        </div>
      <% end %>
    </div>
    <div class="main-app-container my-bg-ligth">
    
    <%= validate_session %>
    </div>
  </body>
</html>